name: Main

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Installing tools
        shell: bash
        run: |
          choco install -y wget --no-progress
          choco install -y pkgconfiglite --no-progress
      - name: Install libvips
        shell: bash
        run: |
          mkdir "C:\Program Files\Vips"
          wget -P "C:\Program Files\Vips" https://github.com/libvips/build-win64-mxe/releases/download/v8.15.0-rc1/vips-dev-w64-all-8.15.0-rc1.zip
          cd 'C:\Program Files\Vips'
          7z x vips-dev-w64-all-8.15.0-rc1.zip -y
          ls vips-dev-8.15
          echo 'C:\Program Files\Vips\vips-dev-8.15\bin' >> $GITHUB_PATH
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
          version: 12.2.0
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21.3'
      - run: go version
      - name: Install Go dependencies
        shell: bash
        run: |
          cd "${{ github.workspace }}"
          go get github.com/go-ole/go-ole
          go get github.com/google/uuid
          go get github.com/h2non/bimg@0fdc5cc0e1b83a1d81c2f8ff73ad9aaad614f2c7
          go get github.com/harry1453/go-common-file-dialog
          go get golang.org/x/exp
          go get golang.org/x/sys
      - name: Test project
        shell: bash
        run: |
          export PKG_CONFIG_PATH='C:\Program Files\Vips\vips-dev-8.15\lib\pkgconfig'
          make tests
      - name: Build for Windows Vista
        shell: bash
        run: |
          make build_for_windows WIN_EXE_NAME="imageConverter.exe"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          draft: true
          files: |
            imageConverter.exe